import "@/styles/globals.css";
import vazirFont from "@/constants/localFont";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${vazirFont.variable} font-sans min-h-screen`}>
        {children}
      </body>
    </html>
  );
}
